github: [AbirKundu, user2, user3, user4] # Replace with your GitHub Sponsors-enabled username and up to 3 more
patreon: abirkundu # Replace with your Patreon username
open_collective: abirkundu # Replace with your Open Collective username
ko_fi: abirkundu # Replace with your Ko-fi username
tidelift: npm/abirkundu # Replace with your Tidelift platform/package name
community_bridge: cloud-foundry # Replace with your Community Bridge project name
liberapay: abirkundu # Replace with your Liberapay username
issuehunt: abirkundu # Replace with your IssueHunt username
lfx_crowdfunding: cloud-foundry # Replace with your LFX Crowdfunding project name
polar: abirkundu # Replace with your Polar username
buy_me_a_coffee: abirkundu # Replace with your Buy Me a Coffee username
thanks_dev: abirkundu # Replace with your thanks.dev username
custom: ['https://link1.com', 'https://link2.com'] # Replace with up to 4 custom sponsorship URLs
